# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Package util
    
on:
  release:
    types: [created,edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: make all/build

  publish-storage:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run ${{github.event.release.tag_name}}
        working-directory: ./utils/storage
      - run: make build
        working-directory: ./utils/storage
      - run: npm publish
        working-directory: ./utils/storage
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-promise:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run ${{github.event.release.tag_name}}
        working-directory: ./utils/promise
      - run: make build
        working-directory: ./utils/promise
      - run: npm publish
        working-directory: ./utils/promise
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
